# Generated by Django 2.0.5 on 2019-04-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='interviews',
        ),
        migrations.AlterField(
            model_name='input',
            name='dbms',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Grade in DBMS '),
        ),
        migrations.AlterField(
            model_name='input',
            name='dsa',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Grade in DSA'),
        ),
        migrations.AlterField(
            model_name='input',
            name='networks',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Grade in Networks'),
        ),
        migrations.AlterField(
            model_name='input',
            name='os',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Grade in Operating Sytems'),
        ),
    ]
