# Generated by Django 2.0.5 on 2019-04-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptive_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('category', models.CharField(choices=[('1', 'E->D'), ('2', 'D->C'), ('3', 'C->B'), ('4', 'B->A'), ('5', 'A->S')], max_length=1)),
                ('subject', models.CharField(choices=[('OS', 'OS'), ('DBMS', 'DBMS'), ('DSA', 'DSA'), ('NET', 'NETWORKS')], max_length=7)),
                ('a_choice', models.CharField(max_length=10000)),
                ('b_choice', models.CharField(max_length=10000)),
                ('c_choice', models.CharField(max_length=10000)),
                ('d_choice', models.CharField(max_length=10000)),
                ('correct', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('OS', 'OS'), ('DBMS', 'DBMS'), ('DSA', 'DSA'), ('NET', 'NETWORKS')], max_length=7),
        ),
    ]
